#!/usr/bin/env bash
# scripts/dev-bootstrap.sh
#
# Runs once after `distrobox assemble create` or in the dev Dockerfile's
# equivalent hook. Idempotent: safe to re-run. We ALWAYS download to a
# temp file first, then verify, then extract — never pipe curl straight
# into tar (see Dockerfile.gott-dev for rationale).
#
# Inside a distrobox the user is non-root by default, but `ln -sf` to
# /usr/local/lib and `ldconfig` both need privileges. We try sudo first
# and fall back to direct execution when already root.

set -euo pipefail

ORT_VER="${ORT_VER:-1.18.0}"
GO_VERSION="${GO_VERSION:-1.23.4}"
ORT_DIR="/opt/onnxruntime-linux-x64-${ORT_VER}"

# `sudo` if non-root, nothing if already root.
if [[ "$(id -u)" -eq 0 ]]; then
    PRIV=""
else
    if command -v sudo >/dev/null 2>&1; then
        PRIV="sudo -n"
    else
        echo "==> need root or sudo to install ONNX Runtime into /opt; aborting" >&2
        exit 1
    fi
fi

echo "==> installing Go ${GO_VERSION}"
if ! go version 2>/dev/null | grep -q "go${GO_VERSION}"; then
    TMPGO="$(mktemp --suffix=.tgz)"
    curl -fsSL -o "${TMPGO}" \
        "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
    $PRIV tar -C /usr/local -xzf "${TMPGO}"
    rm -f "${TMPGO}"
fi

echo "==> installing ONNX Runtime v${ORT_VER}"
if [[ ! -f "${ORT_DIR}/lib/libonnxruntime.so" ]]; then
    TMPTAR="$(mktemp --suffix=.tgz)"
    curl -fsSL -o "${TMPTAR}" \
        "https://github.com/microsoft/onnxruntime/releases/download/v${ORT_VER}/onnxruntime-linux-x64-${ORT_VER}.tgz"
    $PRIV mkdir -p /opt
    $PRIV tar -C /opt -xzf "${TMPTAR}"
    rm -f "${TMPTAR}"
fi

echo "==> linking libonnxruntime.so"
$PRIV ln -sf "${ORT_DIR}/lib/libonnxruntime.so" /usr/local/lib/libonnxruntime.so
$PRIV ldconfig

# Wire LD_LIBRARY_PATH for the active user. /etc/profile.d is the
# distrobox-friendly location (it survives box rebuild).
if [[ ! -f /etc/profile.d/gott-ort.sh ]]; then
    $PRIV tee /etc/profile.d/gott-ort.sh >/dev/null <<EOF
# Auto-generated by scripts/dev-bootstrap.sh
export LD_LIBRARY_PATH="${ORT_DIR}/lib:\${LD_LIBRARY_PATH:-}"
export GOTT_ORT_LIB="${ORT_DIR}/lib/libonnxruntime.so"
EOF
    $PRIV chmod 0644 /etc/profile.d/gott-ort.sh
fi

# Also make sure the Go path ends up in PATH for non-login shells.
if ! grep -q "/usr/local/go/bin" "${HOME}/.bashrc" 2>/dev/null; then
    {
        echo ""
        echo "# gott: Go toolchain installed by scripts/dev-bootstrap.sh"
        echo "export PATH=\"/usr/local/go/bin:\${PATH}\""
    } >> "${HOME}/.bashrc"
fi

echo "==> done. ONNX Runtime at ${ORT_DIR}"
echo "    run 'source /etc/profile.d/gott-ort.sh' to load the env in this shell."
